
name: AppInspect
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - '.github/**'
      - "docs/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - '.github/**'

jobs:
   build:
     uses: diogofgm/splunk-appinspect-action/.github/workflows/splunk-appinspect-action.yaml@v0.0.3
